### ISSUE TITLE
Hessian serialization problem

### ISSUE THREAD

**Issue by wavesZh** [sofastack/sofa-hessian#52]
在[泛化序列化](https://github.com/sofastack/sofa-hessian/wiki/UserGuide#%E6%B3%9B%E5%8C%96%E5%BA%8F%E5%88%97%E5%8C%96)的例子里面， 如果将 Hessian2Output 和 Hessian2Input 换成 HessianOutput 和 HessianInput，程序会执行失败：

```
Exception in thread "main" com.caucho.hessian.io.HessianProtocolException: unknown code:￿
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1717)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1203)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:221)
	at com.caucho.hessian.io.JavaDeserializer.readMap(JavaDeserializer.java:161)
	at com.caucho.hessian.io.SerializerFactory.readMap(SerializerFactory.java:380)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1186)
       ... ... 
```
是否限制了只能使用 Hessian2 呢？ 

com.alipay.sofa:hessian 版本 = 3.3.7

**Comment by ujjboy** [comment]
是的，只支持了 Hessian2 协议。
